name: music_streaming_app
description: A simple music streaming app built with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  audioplayers: ^6.1.0 
  audio_service: ^0.18.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.3
  json_serializable: ^6.2.0
  shared_preferences: ^2.1.0
  flutter_secure_storage: ^6.1.0
  fluttertoast: ^8.1.0
  url_launcher: ^6.1.7
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  logger: ^1.1.0
  flutter_dotenv: ^5.0.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true




